"""add position groups

Revision ID: 083f08190d6a
Revises: 3b1b1b34b20b
Create Date: 2026-05-15 23:09:12.097918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083f08190d6a'
down_revision: Union[str, None] = '3b1b1b34b20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['position_groups.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['option_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_group_members_position_id'), ['position_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_group_members_position_id'))
        batch_op.drop_index(batch_op.f('ix_position_group_members_group_id'))

    op.drop_table('position_group_members')
    op.drop_table('position_groups')
    # ### end Alembic commands ###
