"""add wheel cycles

Revision ID: 3100d48361d0
Revises: 083f08190d6a
Create Date: 2026-05-16 00:23:18.624866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3100d48361d0'
down_revision: Union[str, None] = '083f08190d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('shares_held', sa.Integer(), nullable=False),
    sa.Column('avg_cost_basis', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('options_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('num_puts', sa.Integer(), nullable=False),
    sa.Column('num_calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wheel_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_cycles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_cycles_symbol'), ['symbol'], unique=False)

    op.create_table('wheel_cycle_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=4), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['wheel_cycles.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['option_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wheel_cycle_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_cycle_members_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_cycle_members_position_id'), ['position_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wheel_cycle_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_cycle_members_position_id'))
        batch_op.drop_index(batch_op.f('ix_wheel_cycle_members_cycle_id'))

    op.drop_table('wheel_cycle_members')
    with op.batch_alter_table('wheel_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_cycles_symbol'))
        batch_op.drop_index(batch_op.f('ix_wheel_cycles_status'))

    op.drop_table('wheel_cycles')
    # ### end Alembic commands ###
