"""underlying_trades.position_id nullable

Revision ID: 3a8ae343490d
Revises: 3100d48361d0
Create Date: 2026-05-16 00:29:03.566304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8ae343490d'
down_revision: Union[str, None] = '3100d48361d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underlying_trades', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underlying_trades', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
