"""add volatility_override to positions

Revision ID: 3b1b1b34b20b
Revises: 88b2b282ef13
Create Date: 2026-05-15 23:08:24.856343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1b1b34b20b'
down_revision: Union[str, None] = '88b2b282ef13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volatility_override', sa.Numeric(precision=6, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_positions', schema=None) as batch_op:
        batch_op.drop_column('volatility_override')

    # ### end Alembic commands ###
