"""baseline schema

Revision ID: 88b2b282ef13
Revises: 
Create Date: 2026-05-15 23:07:51.643111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b2b282ef13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('option_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contract_unique', ['symbol', 'expiration', 'strike', 'option_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_option_contracts_symbol'), ['symbol'], unique=False)

    op.create_table('stocknear_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('data_json', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocknear_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocknear_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_stocknear_cache_data_type'), ['data_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocknear_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocknear_cache_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index('ix_stocknear_cache_lookup', ['cache_key', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocknear_cache_symbol'), ['symbol'], unique=False)

    op.create_table('option_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('total_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('num_contracts', sa.Integer(), nullable=False),
    sa.Column('underlying_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['option_contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    with op.batch_alter_table('option_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_positions_is_closed'), ['is_closed'], unique=False)

    op.create_table('option_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_symbol', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['option_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('option_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_trades_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_trades_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index('ix_trade_date_contract', ['trade_date', 'contract_id'], unique=False)

    op.create_table('underlying_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['option_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('underlying_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_underlying_trades_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_underlying_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_underlying_trades_trade_date'), ['trade_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underlying_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_underlying_trades_trade_date'))
        batch_op.drop_index(batch_op.f('ix_underlying_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_underlying_trades_position_id'))

    op.drop_table('underlying_trades')
    with op.batch_alter_table('option_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_date_contract')
        batch_op.drop_index(batch_op.f('ix_option_trades_trade_date'))
        batch_op.drop_index(batch_op.f('ix_option_trades_contract_id'))

    op.drop_table('option_trades')
    with op.batch_alter_table('option_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_positions_is_closed'))

    op.drop_table('option_positions')
    with op.batch_alter_table('stocknear_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocknear_cache_symbol'))
        batch_op.drop_index('ix_stocknear_cache_lookup')
        batch_op.drop_index(batch_op.f('ix_stocknear_cache_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_stocknear_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_stocknear_cache_data_type'))
        batch_op.drop_index(batch_op.f('ix_stocknear_cache_cache_key'))

    op.drop_table('stocknear_cache')
    with op.batch_alter_table('option_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_contracts_symbol'))
        batch_op.drop_index('ix_contract_unique')

    op.drop_table('option_contracts')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
