"""add contract history

Revision ID: c9bece88f667
Revises: 3a8ae343490d
Create Date: 2026-08-19 17:02:34.205495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bece88f667'
down_revision: Union[str, None] = '3a8ae343490d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bid', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ask', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mark', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('change_oi', sa.Integer(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('changes_percentage_oi', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.Column('epsilon', sa.Float(), nullable=True),
    sa.Column('lambda', sa.Float(), nullable=True),
    sa.Column('charm', sa.Float(), nullable=True),
    sa.Column('vanna', sa.Float(), nullable=True),
    sa.Column('vomma', sa.Float(), nullable=True),
    sa.Column('veta', sa.Float(), nullable=True),
    sa.Column('vera', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('zomma', sa.Float(), nullable=True),
    sa.Column('color', sa.Float(), nullable=True),
    sa.Column('ultima', sa.Float(), nullable=True),
    sa.Column('gex', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('dex', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('total_premium', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['option_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_history_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_history_date'), ['date'], unique=False)
        batch_op.create_index('ix_contract_history_unique', ['contract_id', 'date'], unique=True)

    op.create_table('contract_history_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['option_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_history_sync', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_history_sync_contract_id'), ['contract_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_history_sync', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_history_sync_contract_id'))

    op.drop_table('contract_history_sync')
    with op.batch_alter_table('contract_history', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_history_unique')
        batch_op.drop_index(batch_op.f('ix_contract_history_date'))
        batch_op.drop_index(batch_op.f('ix_contract_history_contract_id'))

    op.drop_table('contract_history')
    # ### end Alembic commands ###
